export const defaultExpenseCategories = [
  "Food & Dining",
  "Transportation",
  "Utilities",
  "Groceries",
  "Housing/Rent",
  "Insurance",
  "Healthcare",
  "Entertainment",
  "Shopping",
  "Travel",
  "Education",
  "Debt Payments",
  "Investments",
  "Savings",
  "Personal Care",
  "Gifts & Donations",
  "Taxes",
  "Miscellaneous",
];

export const defaultIncomeCategories = [
  "Salary",
  "Business",
  "Freelance",
  "Investments",
  "Rental Income",
  "Interest",
  "Dividends",
  "Capital Gains",
  "Pension",
  "Gifts",
  "Bonuses",
  "Commissions",
  "Royalties",
  "Government Benefits",
  "Other Income",
];
