import mongoose from "mongoose";

const transactionSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
  name: { type: String, required: true },
  type: { type: String, enum: ["income", "expense", "saving", "transfer"], required: true },
  amount: { type: Number, required: true },
  category: { type: String, required: true },
  note: { type: String },
  date: { type: Date, default: Date.now },

  // Account this transaction affected (the "pocket" money moved from/into).
  // For a transfer, `accountId` is the SOURCE and `toAccountId` the DESTINATION.
  // Defaults to the user's default account when not provided on create.
  accountId: { type: mongoose.Schema.Types.ObjectId, ref: "Account", default: null },
  toAccountId: { type: mongoose.Schema.Types.ObjectId, ref: "Account", default: null },

  // Debt link — set on EMI interest expenses and principal repayments so a
  // loan's payment history stays traceable (Phase 2).
  debtId: { type: mongoose.Schema.Types.ObjectId, ref: "Debt", default: null },

  // Bill link — set when a transaction was generated by paying a scheduled
  // payment/bill (Phase 3), so bill payment history stays traceable.
  billId: { type: mongoose.Schema.Types.ObjectId, ref: "ScheduledPayment", default: null },

  // Lending link (Phase 4) — set on money lent/borrowed and its repayments.
  // These are single-sided transfers: they move real account balances but are
  // hidden from the main transaction list (managed on the Lending page instead).
  lendingId: { type: mongoose.Schema.Types.ObjectId, ref: "Lending", default: null },

  // Recurring fields
  isRecurring: { type: Boolean, default: false },
  recurringId: { type: mongoose.Schema.Types.ObjectId, ref: "RecurringRule", default: null },

  // Savings link — set when this transaction is a contribution to / withdrawal
  // from a savings goal, so goal activity stays traceable.
  savingsGoalId: { type: mongoose.Schema.Types.ObjectId, ref: "SavingsGoal", default: null },

  // Event planning fields
  // When set, this transaction belongs to a big event (marriage, vacation, …).
  eventId: { type: mongoose.Schema.Types.ObjectId, ref: "Event", default: null },
  // A planned/future spend counts toward the event plan but is excluded from
  // the user's current balance and the main transaction list until confirmed.
  isPlanned: { type: Boolean, default: false }
}, { timestamps: true });

export default mongoose.model("Transaction", transactionSchema);
